
package fr.mb.biblio.webappConsumer.services.identification;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "identificationServiceImplService", targetNamespace = "http://identification.soap.biblio.mb.fr/", wsdlLocation = "http://localhost:8080/identificationService?wsdl")
public class IdentificationServiceImplService
    extends Service
{

    private final static URL IDENTIFICATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IDENTIFICATIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName IDENTIFICATIONSERVICEIMPLSERVICE_QNAME = new QName("http://identification.soap.biblio.mb.fr/", "identificationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/identificationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDENTIFICATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        IDENTIFICATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public IdentificationServiceImplService() {
        super(__getWsdlLocation(), IDENTIFICATIONSERVICEIMPLSERVICE_QNAME);
    }

    public IdentificationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDENTIFICATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public IdentificationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, IDENTIFICATIONSERVICEIMPLSERVICE_QNAME);
    }

    public IdentificationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDENTIFICATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public IdentificationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdentificationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IdentificationService
     */
    @WebEndpoint(name = "identificationServiceImplPort")
    public IdentificationService getIdentificationServiceImplPort() {
        return super.getPort(new QName("http://identification.soap.biblio.mb.fr/", "identificationServiceImplPort"), IdentificationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdentificationService
     */
    @WebEndpoint(name = "identificationServiceImplPort")
    public IdentificationService getIdentificationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://identification.soap.biblio.mb.fr/", "identificationServiceImplPort"), IdentificationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDENTIFICATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw IDENTIFICATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return IDENTIFICATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
