
package fr.mb.biblio.webappConsumer.services.identification;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "identificationService", targetNamespace = "http://identification.soap.biblio.mb.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IdentificationService {


    /**
     * 
     * @param identifiant
     * @param mdp
     * @return
     *     returns fr.mb.biblio.webappConsumer.services.identification.Utilisateur
     * @throws NotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "identification", targetNamespace = "http://identification.soap.biblio.mb.fr/", className = "fr.mb.biblio.webappConsumer.services.identification.Identification")
    @ResponseWrapper(localName = "identificationResponse", targetNamespace = "http://identification.soap.biblio.mb.fr/", className = "fr.mb.biblio.webappConsumer.services.identification.IdentificationResponse")
    public Utilisateur identification(
        @WebParam(name = "identifiant", targetNamespace = "")
        String identifiant,
        @WebParam(name = "mdp", targetNamespace = "")
        String mdp)
        throws NotFoundException_Exception
    ;

}
