
package fr.mb.biblio.batch.service.pret;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotFoundException", targetNamespace = "http://contract.pretService.soap.biblio.mb.fr/")
public class NotFoundException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NotFoundException_Exception(String message, NotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NotFoundException_Exception(String message, NotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.mb.biblio.batch.service.pret.NotFoundException
     */
    public NotFoundException getFaultInfo() {
        return faultInfo;
    }

}
