package fr.mb.biblio.models.beans;
// Generated 17 mai 2018 21:05:11 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.inject.Named;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Auteur generated by hbm2java
 */
@Entity
@Table(name = "auteur", schema = "public")
public class Auteur implements java.io.Serializable {

	private int idAuteur;
	private String prenom;
	private String nom;
	private Set<Livre> livres = new HashSet<Livre>(0);

	public Auteur() {
	}

	public Auteur(int idAuteur, String prenom, String nom) {
		this.idAuteur = idAuteur;
		this.prenom = prenom;
		this.nom = nom;
	}

	public Auteur(int idAuteur, String prenom, String nom, Set<Livre> livres) {
		this.idAuteur = idAuteur;
		this.prenom = prenom;
		this.nom = nom;
		this.livres = livres;
	}

	@Id

	@Column(name = "id_auteur", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getIdAuteur() {
		return this.idAuteur;
	}

	public void setIdAuteur(int idAuteur) {
		this.idAuteur = idAuteur;
	}

	@Column(name = "prenom", nullable = false)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "auteurs")
	public Set<Livre> getLivres() {
		return this.livres;
	}

	public void setLivres(Set<Livre> livres) {
		this.livres = livres;
	}

}
