package fr.mb.biblio.models.beans;
// Generated 17 mai 2018 21:05:11 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Editeur generated by hbm2java
 */
@Entity
@Table(name = "editeur", schema = "public")
public class Editeur implements java.io.Serializable {

	private int idEditeur;
	private String nom;
	private Set<Livre> livres = new HashSet<Livre>(0);

	public Editeur() {
	}

	public Editeur(int idEditeur, String nom) {
		this.idEditeur = idEditeur;
		this.nom = nom;
	}

	public Editeur(int idEditeur, String nom, Set<Livre> livres) {
		this.idEditeur = idEditeur;
		this.nom = nom;
		this.livres = livres;
	}

	@Id

	@Column(name = "id_editeur", unique = true, nullable = false)
	public int getIdEditeur() {
		return this.idEditeur;
	}

	public void setIdEditeur(int idEditeur) {
		this.idEditeur = idEditeur;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "editeurs")
	public Set<Livre> getLivres() {
		return this.livres;
	}

	public void setLivres(Set<Livre> livres) {
		this.livres = livres;
	}

}
