package fr.mb.biblio.models.beans;
// Generated 17 mai 2018 21:05:11 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Livre generated by hbm2java
 */
@Entity
@Table(name = "livre", schema = "public")
public class Livre implements java.io.Serializable {

	private int idLivre;
	private Ouvrage ouvrage;
	private String titre;
	private Date parution;
	private String image;
	private String resume;
	private Set<Auteur> auteurs = new HashSet<Auteur>(0);
	private Set<Genre> genres = new HashSet<Genre>(0);
	private Set<Editeur> editeurs = new HashSet<Editeur>(0);
	private Set<Pret> prets = new HashSet<Pret>(0);

	public Livre() {
	}

	public Livre(int idLivre, Ouvrage ouvrage, String titre, Date parution, String image, String resume) {
		this.idLivre = idLivre;
		this.ouvrage = ouvrage;
		this.titre = titre;
		this.parution = parution;
		this.image = image;
		this.resume = resume;
	}

	public Livre(int idLivre, Ouvrage ouvrage, String titre, Date parution, String image, String resume,
			Set<Auteur> auteurs, Set<Genre> genres, Set<Editeur> editeurs, Set<Pret> prets) {
		this.idLivre = idLivre;
		this.ouvrage = ouvrage;
		this.titre = titre;
		this.parution = parution;
		this.image = image;
		this.resume = resume;
		this.auteurs = auteurs;
		this.genres = genres;
		this.editeurs = editeurs;
		this.prets = prets;
	}

	@Id

	@Column(name = "id_livre", unique = true, nullable = false)
	public int getIdLivre() {
		return this.idLivre;
	}

	public void setIdLivre(int idLivre) {
		this.idLivre = idLivre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ouvrage", nullable = false)
	public Ouvrage getOuvrage() {
		return this.ouvrage;
	}

	public void setOuvrage(Ouvrage ouvrage) {
		this.ouvrage = ouvrage;
	}

	@Column(name = "titre", nullable = false)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parution", nullable = false, length = 13)
	public Date getParution() {
		return this.parution;
	}

	public void setParution(Date parution) {
		this.parution = parution;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "resume", nullable = false)
	public String getResume() {
		return this.resume;
	}

	public void setResume(String resume) {
		this.resume = resume;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "livre_auteur", schema = "public", joinColumns = {
			@JoinColumn(name = "id_livre", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_auteur", nullable = false, updatable = false) })
	public Set<Auteur> getAuteurs() {
		return this.auteurs;
	}

	public void setAuteurs(Set<Auteur> auteurs) {
		this.auteurs = auteurs;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "livre_genre", schema = "public", joinColumns = {
			@JoinColumn(name = "id_livre", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_genre", nullable = false, updatable = false) })
	public Set<Genre> getGenres() {
		return this.genres;
	}

	public void setGenres(Set<Genre> genres) {
		this.genres = genres;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "livre_editeur", schema = "public", joinColumns = {
			@JoinColumn(name = "id_livre", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_editeur", nullable = false, updatable = false) })
	public Set<Editeur> getEditeurs() {
		return this.editeurs;
	}

	public void setEditeurs(Set<Editeur> editeurs) {
		this.editeurs = editeurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "livre")
	public Set<Pret> getPrets() {
		return this.prets;
	}

	public void setPrets(Set<Pret> prets) {
		this.prets = prets;
	}

}
