package fr.mb.biblio.models.beans;
// Generated 17 mai 2018 21:05:11 by Hibernate Tools 5.2.10.Final

import java.time.LocalDate;
import java.util.Date;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import fr.mb.biblio.models.LocalDateXmlAdapter;

/**
 * Pret generated by hbm2java
 */
@Entity
@Table(name = "pret", catalog = "projet")
@XmlRootElement
public class Pret implements java.io.Serializable {

	private int idPret;
	private Livre livre;
	private Utilisateur utilisateur;
	private LocalDate dateDebut;
	private LocalDate dateFin;
	private LocalDate dateEffective;
	private boolean prolonge;

	public Pret() {
	}

	public Pret(int idPret, Livre livre, Utilisateur utilisateur, LocalDate dateDebut, LocalDate dateFin, LocalDate dateEffective,
			boolean prolonge) {
		this.idPret = idPret;
		this.livre = livre;
		this.utilisateur = utilisateur;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.dateEffective = dateEffective;
		this.prolonge = prolonge;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_pret", unique = true, nullable = false)
	public int getIdPret() {
		return this.idPret;
	}

	public void setIdPret(int idPret) {
		this.idPret = idPret;
	}
	
	
	@ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
	@JoinColumn(name = "id_livre", nullable = false)
	public Livre getLivre() {
		return this.livre;
	}

	public void setLivre(Livre livre) {
		livre.getPrets().add(this);
		this.livre = livre;
	}
	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_utilisateur", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
	@XmlSchemaType(name = "date")
	@Column(name = "date_debut", nullable = false, length = 13)
	public LocalDate getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(LocalDate dateDebut2) {
		this.dateDebut = dateDebut2;
	}

	@XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
	@XmlSchemaType(name = "date")
	@Column(name = "date_fin", nullable = false, length = 13)
	public LocalDate getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(LocalDate dateFin) {
		this.dateFin = dateFin;
	}

	@XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
	@XmlSchemaType(name = "date")
	@Column(name = "date_effective", nullable = true, length = 13)
	public LocalDate getDateEffective() {
		return this.dateEffective;
	}

	public void setDateEffective(LocalDate dateEffective) {
		this.dateEffective = dateEffective;
	}

	@Column(name = "prolonge", nullable = false)
	public boolean isProlonge() {
		return this.prolonge;
	}

	public void setProlonge(boolean prolonge) {
		this.prolonge = prolonge;
	}

}
