package fr.mb.biblio.models.beans;
// Generated 17 mai 2018 21:05:11 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.inject.Named;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */

@Entity
@Table(name = "utilisateur", catalog = "projet")
public class Utilisateur implements java.io.Serializable {

	private int idUtilisateur;
	private String identifiant;
	private String prenom;
	private String nom;
	private String mdp;
	private String mail;
	private Set<Pret> prets = new HashSet<Pret>(0);

	public Utilisateur() {
	}

	public Utilisateur(int idUtilisateur, String identifiant, String prenom, String nom, String mdp, String mail) {
		this.idUtilisateur = idUtilisateur;
		this.identifiant = identifiant;
		this.prenom = prenom;
		this.nom = nom;
		this.mdp = mdp;
		this.mail = mail;
	}

	public Utilisateur(int idUtilisateur, String identifiant, String prenom, String nom, String mdp, String mail,
			Set<Pret> prets) {
		this.idUtilisateur = idUtilisateur;
		this.identifiant = identifiant;
		this.prenom = prenom;
		this.nom = nom;
		this.mdp = mdp;
		this.mail = mail;
		this.prets = prets;
	}

	@Id

	@Column(name = "id_utilisateur", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "identifiant", nullable = false)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "prenom", nullable = false)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "mdp", nullable = false)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	@Column(name = "mail", nullable = false)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "utilisateur")
	public Set<Pret> getPrets() {
		return this.prets;
	}

	public void setPrets(Set<Pret> prets) {
		this.prets = prets;
	}

}
