package fr.mb.biblio.models.beans;
// Generated 17 mai 2018 21:05:11 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.inject.Named;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Utilisateur generated by hbm2java
 */

@Entity
@Table(name = "utilisateur", catalog = "projet")
public class Utilisateur implements java.io.Serializable {

	private int idUtilisateur;
	private String identifiant;
	private String prenom;
	private String nom;
	private String mdp;
	private String mail;
	private Boolean admin;
	private Boolean relance;
	private Set<Pret> prets = new HashSet<Pret>(0);
	private Set<Reservation> listeResaUser = new HashSet<>();

	public Utilisateur() {
	}

	public Utilisateur(int idUtilisateur, String identifiant, String prenom, String nom, String mdp, String mail, Boolean admin, Boolean relance) {
		this.idUtilisateur = idUtilisateur;
		this.identifiant = identifiant;
		this.prenom = prenom;
		this.nom = nom;
		this.mdp = mdp;
		this.mail = mail;
		this.admin=admin;
		this.relance=relance;
	}

	public Utilisateur(int idUtilisateur, String identifiant, String prenom, String nom, String mdp, String mail, Boolean admin, Boolean relance,
			Set<Pret> prets,Set<Reservation> listeResaUser) {
		this.idUtilisateur = idUtilisateur;
		this.identifiant = identifiant;
		this.prenom = prenom;
		this.nom = nom;
		this.mdp = mdp;
		this.mail = mail;
		this.admin=admin;
		this.relance=relance;
		this.prets = prets;
		this.listeResaUser=listeResaUser;
	}

	@Id

	@Column(name = "id_utilisateur", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "identifiant", nullable = false)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "prenom", nullable = false)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
	
	@XmlTransient
	@Column(name = "mdp", nullable = false)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	@Column(name = "mail", nullable = false)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}
	
	@XmlTransient
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "utilisateur")
	public Set<Pret> getPrets() {
		return this.prets;
	}

	public void setPrets(Set<Pret> prets) {
		this.prets = prets;
	}
	@Column(name = "admin")
	public Boolean getAdmin() {
		return admin;
	}

	public void setAdmin(Boolean admin) {
		this.admin = admin;
	}

	@Column(name="relance")
	public Boolean getRelance() {
		return relance;
	}

	public void setRelance(Boolean relance) {
		this.relance = relance;
	}

	@XmlTransient
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "demandeur")
	public Set<Reservation> getListeResaUser() {
		return listeResaUser;
	}

	public void setListeResaUser(Set<Reservation> listeResaUser) {
		this.listeResaUser = listeResaUser;
	}
}
