
package fr.mb.biblio.webapp.services.livre;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LivreServiceImplService", targetNamespace = "http://impl.livreService.soap.biblio.mb.fr/", wsdlLocation = "http://192.168.99.100:8081/SOAP/livreService?wsdl")
public class LivreServiceImplService
    extends Service
{

    private final static URL LIVRESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIVRESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName LIVRESERVICEIMPLSERVICE_QNAME = new QName("http://impl.livreService.soap.biblio.mb.fr/", "LivreServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.99.100:8081/SOAP/livreService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIVRESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LIVRESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LivreServiceImplService() {
        super(__getWsdlLocation(), LIVRESERVICEIMPLSERVICE_QNAME);
    }

    public LivreServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIVRESERVICEIMPLSERVICE_QNAME, features);
    }

    public LivreServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LIVRESERVICEIMPLSERVICE_QNAME);
    }

    public LivreServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIVRESERVICEIMPLSERVICE_QNAME, features);
    }

    public LivreServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LivreServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LivreService
     */
    @WebEndpoint(name = "LivreServiceImplPort")
    public LivreService getLivreServiceImplPort() {
        return super.getPort(new QName("http://impl.livreService.soap.biblio.mb.fr/", "LivreServiceImplPort"), LivreService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LivreService
     */
    @WebEndpoint(name = "LivreServiceImplPort")
    public LivreService getLivreServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.livreService.soap.biblio.mb.fr/", "LivreServiceImplPort"), LivreService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIVRESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LIVRESERVICEIMPLSERVICE_EXCEPTION;
        }
        return LIVRESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
