
package fr.mb.biblio.webapp.services.pret;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FunctionalException", targetNamespace = "http://contract.pretService.soap.biblio.mb.fr/")
public class FunctionalException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FunctionalException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FunctionalException_Exception(String message, FunctionalException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FunctionalException_Exception(String message, FunctionalException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.mb.biblio.webapp.services.pret.FunctionalException
     */
    public FunctionalException getFaultInfo() {
        return faultInfo;
    }

}
